name: CI
on: workflow_dispatch
jobs:
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print A
        run: echo "JE SUIS LA"
      - name: Print B
        run: echo "JE SUIS PAS LA"
  
